/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversordemonedas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author CARLOS
 */
public class mainConversor extends javax.swing.JFrame {

    /**
     * Creates new form mainConversor
     */
    
        private static final double PESOAMERICANO = 4911.48d;
        private static final double METRO = 1000;
        private double operacion = 0.0d;
    public mainConversor() {
        setSize(new Dimension(350, 470));
        setLayout(new FlowLayout());
        initComponents();
        this.setLocationRelativeTo(null);
        Border border = BorderFactory.createLineBorder(Color.DARK_GRAY, 2, true);
        txtMoneda.setBorder(border);
        txtMoneda.setBackground(Color.white);
        txtMoneda.setForeground(Color.BLACK);

        txtResultado.setBorder(border);
        txtResultado.setBackground(Color.DARK_GRAY);
        txtResultado.setForeground(Color.white);

        btnConvertir.setBorder(border);
        btnConvertir.setBackground(Color.white);
        btnConvertir.setForeground(Color.BLACK);

        comboBoxCustom2.addItem("Seleccionar");
        comboBoxCustom2.addItem("De Peso Colombiano a Dolar Americano");
        comboBoxCustom2.addItem("De Dolar Americano a Peso Colombiano");
        comboBoxCustom2.addItem("De Km a Metros");
        comboBoxCustom2.addItem("De Metros a Km");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboBoxCustom2 = new ConversorComboBox.ComboBoxCustom();
        txtMoneda = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Monedas");
        setName("conversor"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        comboBoxCustom2.setPreferredSize(new java.awt.Dimension(245, 42));

        txtMoneda.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtResultado.setBackground(new java.awt.Color(102, 102, 102));
        txtResultado.setForeground(new java.awt.Color(255, 255, 255));
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultado.setText("RESULTADO");
        txtResultado.setEnabled(false);

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMoneda)
                            .addComponent(comboBoxCustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(248, 248, 248))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(comboBoxCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
        // de peso colombiano a dolar americano
        // dolar hoy: 4911.48 
        System.out.println(comboBoxCustom2.getSelectedIndex());
        DecimalFormat formato1 = new DecimalFormat("#.#####");
        try {
            NumberFormat formatoImporte = NumberFormat.getCurrencyInstance(new Locale("es", "CO"));
            double valorAConvertir = Double.parseDouble(txtMoneda.getText());
            // caso donde sea de peso colombiano a peso americano / dolar
            
            switch (comboBoxCustom2.getSelectedIndex()) {
                case 1 -> {
                    operacion = valorAConvertir / PESOAMERICANO;
                    txtResultado.setText(formatoImporte.format(operacion));
                }
                case 2 -> {
                    operacion = valorAConvertir * PESOAMERICANO;
                    txtResultado.setText(formatoImporte.format(operacion));
                }
                case 3 -> {
                    operacion = valorAConvertir * METRO;
                    txtResultado.setText(formato1.format(operacion));
                }
                case 4 -> {
                    operacion = valorAConvertir / METRO;
                    txtResultado.setText(formato1.format(operacion));
                }
                default -> txtResultado.setText("No ha seleciconado ningun valor!");
            }
            
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, nfe);
        }

    }//GEN-LAST:event_btnConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainConversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private ConversorComboBox.ComboBoxCustom comboBoxCustom2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMoneda;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables

}
